# Generated by Django 5.1 on 2024-08-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setup',
            },
        ),
        migrations.AddField(
            model_name='menulink',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=255),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_pagination',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='title',
            field=models.CharField(default='Sem Title', max_length=65),
        ),
    ]
